import json
import random

def enhance_message(msg):
    """
    Simple rule-based booster for creative messages.
    """
    boosters = [
        "Limited Time Offer!",
        "Shop Now & Save Big!",
        "Exclusive Deal Inside!",
        "Don't Miss Out!",
        "Try It Today!",
        "Your Perfect Fit Awaits!"
    ]
    ctas = [
        "Shop Now",
        "Buy Now",
        "Learn More",
        "Grab the Offer",
        "Explore Collection",
    ]

    return {
        "new_headline": f"{random.choice(boosters)}",
        "new_primary_text": f"{msg} — {random.choice(boosters)}",
        "new_cta": random.choice(ctas),
        "reasoning": "Generated by enhancing emotional triggers, urgency, and clarity."
    }


def generate_creatives(summary):
    low_ctr_campaigns = summary.get("lowest_ctr_campaigns", [])
    sample_creatives = summary.get("sample_creatives_low_ctr", [])

    output = {"campaign_creative_suggestions": []}

    for item in sample_creatives:
        campaign = item.get("campaign_name")
        msg = item.get("creative_message", "")

        improved = enhance_message(msg)

        output["campaign_creative_suggestions"].append({
            "campaign_name": campaign,
            "old_creative_message": msg,
            "new_headline": improved["new_headline"],
            "new_primary_text": improved["new_primary_text"],
            "new_cta": improved["new_cta"],
            "reasoning": improved["reasoning"]
        })

    return output


if __name__ == "__main__":
    with open("reports/data_summary.json") as f:
        summary = json.load(f)

    creatives = generate_creatives(summary)

    with open("reports/creatives.json", "w") as f:
        json.dump(creatives, f, indent=2)

    print("Generated → reports/creatives.json")
